### ISSUE TITLE
Jolie LS doesn't start on Windows 10

### ISSUE THREAD

**Issue by eferos93** [jolie/vscode-jolie#12] opened 2020-10-26 16:35 UTC
I am getting the following error message when the LS is starting:

```
Activating Jolie Language Server
starting "cmd.exe /K jolie.bat -C Location_JolieLS="socket://localhost:9123" main.ol"
c:\Users\Eros\.vscode\extensions\jolie.vscode-jolie-1.3.6\server\src\internal\deployment.iol:26: error: expected inputPort location string. Found token type ID, token content socket
```
The version of the LS is 1.3.6
Windows 10 Pro 64 bit
java 15.0.1 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
jolie version 1.9.1

**Comment by fmontesi** [comment] 2020-10-29 13:21
Can't reproduce. Maybe @bmaschio ?

**Comment by fmontesi** [comment] 2021-12-09 08:02
Should be fixed now :)

**Closed by fmontesi** 2021-12-09 08:02 UTC
